"use client"
import { useChat, } from "ai/react"
import type { Message } from "ai/react"
import { Sender, type Message as WizepromptMessage } from "@prisma/client";
import { useState, useEffect } from "react";
import type { UseChatOptions } from "ai";
import { encode } from 'gpt-tokenizer';
import type { MessageDataInput } from "@/lib/message";

interface ExtendedUseChatOptions extends UseChatOptions {
    messages: Message[];
    temperature: number;
    customInstructions: string;
}

function calculateTokens(input: string): number {
    const tokens: number[] = encode(input)
    return tokens.length
}

function calculateCredits(tokens: number, model: string, isInput: boolean): number {
    // Checks if the message was user created or output by the model to determine the price
    let price: number
    if (isInput) {
        price = model === 'gpt-3.5-turbo' ? Number(process.env.NEXT_PUBLIC_GPT_35_INPUT) : Number(process.env.NEXT_PUBLIC_GPT_4_INPUT)
    } else {
        price = model === 'gpt-3.5-turbo' ? Number(process.env.NEXT_PUBLIC_GPT_35_OUTPUT) : Number(process.env.NEXT_PUBLIC_GPT_4_OUTPUT)
    }
    // GPT pricing per 1000 tokens
    return (tokens/1000) * price
}

async function saveMessage(message: MessageDataInput): Promise<void> {
    try {
        await fetch('/api/messages', {
            method: 'POST',
            body: JSON.stringify(message)
        });
    } catch {
        console.log("Error ocurred while saving message.")
    }
}

export default function ChatComponent(): JSX.Element {
    const [messageData, setMessageData] = useState<Message[]>([])

    const options: ExtendedUseChatOptions = {
        api: '/api/ai/openai/gpt-4',
        initialMessages: messageData,
        messages: messageData,
        temperature: 0.5,
        customInstructions: "",
        // onFinish callback function that runss when the response stream is finished
        // Saves the message generated by the model
        onFinish(message) {
            const tokens: number = calculateTokens(message.content)
            const messageInfo: MessageDataInput = {
                idConversation: 1,
                content: message.content,
                sender: message.role === 'user' ? Sender.USER : Sender.MODEL,
                creditsUsed: calculateCredits(tokens, 'gpt-3.5-turbo', false)
            }
            void saveMessage(messageInfo)
        },
    };

    // set api route that handleSubmit will use and load initial messages
    const { 
        input, // The current value of the input field.
        handleInputChange, // Handler for the onChange event of the input field to control the input's value.
        handleSubmit, // Form submission handler that automatically resets the input field and appends a user message.
         messages, // The current array of chat messages.
         /*
        isLoading, // Boolean flag indicating whether a request is currently in progress.
        stop, // Function that aborts the current request
        reload,//Function to reload the last AI chat response for the given chat history.
        append, //append(message: Message | CreateMessage, chatRequestOptions: { options: { headers, body } }) Function to append a message to the chat, triggering an API call for the AI response.
        error, //An error object returned by SWR, if any.
        */
    } = useChat(options);


    function convertToGptMessage(item: WizepromptMessage): Message {
        const role: "function" | "user" | "assistant" | "system" = item.sender === "USER" ? "user" : "assistant";
        return {
            id: String(item.id),
            role,
            content: item.content,
        };
    }

    /*
    function convertToWizepromptMessage(item: Message): WizepromptMessage {
        let sender: Sender = item.role === "user" ? "USER" : "MODEL";
        return {
            id: Number(item.id),
            idConversation: 1,  // Set this value as needed
            sender: sender,
            content: item.content,
            creditsUsed: 0,  // Set this value as needed
            createdAt: new Date(),  // Set this value as needed
        };
    }
    */


    // Function that fetches data from messages api route and 
    // sets the content of a message to the first content instance
    const getData: () => Promise<void> = async () => {
        const response: Response = await fetch('/api/messages/conversation/1');
        const data: WizepromptMessage[] = await response.json();
        const processedData: Message[] = data.map(convertToGptMessage);
        setMessageData(processedData);
    };


    useEffect(() => {
        void getData()
    })

    return (
        <div>
            {messages.map((message: Message): JSX.Element => {
                return (
                    <div key={message.id}>
                        {/*Displays the name of the person who sent a message*/}
                        {
                            message.role === "assistant"
                                ?
                                <h3 className="text-lg font-semibold mt-2 px-1">
                                    GPT-3.5-turbo
                                </h3>
                                :
                                <h3 className="text-lg font-semibold mt-2 px-1">
                                    User
                                </h3>
                        }

                        {/* Formatting the message */}
                        {message.content.split("\n").map((currentTextBlock: string, index: number) => {
                            if (currentTextBlock === "") {
                                return <p className="px-1" key={message.id + index} />
                            }
                            return <p className="px-1" key={message.id + index} >{currentTextBlock}</p>
                        })}
                    </div>
                )
            })}

            <form className="mt-12" onSubmit={handleSubmit}>
                <p className="p-1">User Message</p>
                <textarea
                    className="mt-2 w-full bg-textarea p-2 rounded-md text-slate-300 shadow-md resize-y"
                    onChange={handleInputChange}
                    placeholder="What are data structures and algorithms?"
                    value={input}
                />
                <div className="flex flex-row">
                    <button 
                        className="rounded-md bg-wizelinered p-2 mt-2"
                        disabled={!input}
                        // Saves user's message when the send button is clicked
                        onClick={() => {
                            const tokens: number = calculateTokens(input)
                            const messageInfo: MessageDataInput = {
                                idConversation: 1,
                                content: input,
                                sender: Sender.USER,
                                creditsUsed: calculateCredits(tokens, 'gpt-3.5-turbo', true)
                            }
                           void saveMessage(messageInfo)
                        }}
                        type="submit"
                    >
                        Send message
                    </button>
                    <p className="p-3 mt-2">Token estimate: {calculateTokens(input)}</p>
                </div>
            </form>
        </div>
    )
}